### ISSUE TITLE
[Request] 增加一个开关，用于选择是否引用对话历史

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/ops-console#157]
### 🥰 需求描述 | Feature Description

增加一个开关项目，允许用户选择是否在对话过程中使用之前的对话历史

<img width="1198" alt="image" src="https://github.com/kubeagi/ops-console/assets/30621793/d5382518-9662-4c8e-963b-c3793e399218">

### 🧐 解决方案 | Proposed Solution

增加一个 `开关`， 用于选择是否开始对话历史

**Comment by bjwswang** [comment]
@liutianyi0801

**Comment by liutianyi0801** [comment]
使用对话历史是指？目前模型有一个配置是对话轮次，指的就是我们保留多少轮对话记录丢给大模型，对话历史开启的话是指引用所有对话消息？

**Comment by bjwswang** [comment]
> 使用对话历史是指？目前模型有一个配置是对话轮次，指的就是我们保留多少轮对话记录丢给大模型，对话历史开启的话是指引用所有对话消息？

对话轮次是对模型使用会话历史时的配置。这里我们加一个开关，默认开启，可以默认给用添加一个
```shell
---
{{ .history }}
The above content is the chat history. Please answer based on it.
```

**Comment by bjwswang** [comment]
@liutianyi0801

**Comment by bjwswang** [comment]
已有其他方案
