### ISSUE TITLE
[Request] 所有的资源状态为异常时，都应该展示异常原因

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/ops-console#158]
### 🥰 需求描述 | Feature Description

额外展示 message

### 🧐 解决方案 | Proposed Solution

展示message

**Comment by bjwswang** [comment]
@liutianyi0801

**Comment by liutianyi0801** [comment]
这个用 bug 列表跟踪了，没有展示异常 message 的已经指派给相关同学跟进了
