### ISSUE TITLE
[Request] 模型仓库中需增加一种新的模型类型 reranking

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/ops-console#235]
### 🥰 需求描述 | Feature Description

目前的模型仓库支持的模型类型有 llm 和embedding，但是后续我们需要在对话中引入reranking能力，reranking能力需要一种新的模型种类。 

### 🧐 解决方案 | Proposed Solution

支持展示新的模型类型 reranking

### 📝 补充信息 | Additional Information

NOTE: 目前我们不支持reranking类型的模型服务部署，需要暂时过滤掉该类型模型的使用

**Comment by bjwswang** [comment]
@liutianyi0801 目前模型多增加了三个字段：
- maxContextLength: 该模型支持的上下文最大长度
- huggingFaceRepo ： 模型在huggingface上的仓库
- modelScopeRepo: 模型在modelscope上的仓库

**Comment by Carrotzpc** [comment]
已增加
