### ISSUE TITLE
[Bug] 创建模型服务-服务规则 滑动输入条应该与后面的数值同步

### ISSUE THREAD

**Issue by 0xff-dev** [kubeagi/ops-console#243]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

https://github.com/kubeagi/arcadia/issues/802

### 🚦 期望结果 | Expected Behavior

滑动的结果与数值一致

**Comment by Carrotzpc** [comment]
产品设计好像并非如此，滑动输入跟后面的数字输入是独立的，需要产品确认下@liutianyi0801 ，不过目前这种设计确实不太友好，看看是否调整下

**Comment by liutianyi0801** [comment]
<img width="410" alt="78e8eec454f42ed74a147af44e85ff3d" src="https://github.com/kubeagi/ops-console/assets/76506250/8aab1330-3485-46fa-b59a-4f2586e6d4bb">

这个方案实现起来复杂程度如何？
可见 jira：http://jira.tenxcloud.21vianet.com/browse/DEVOPS-4232

@Carrotzpc

**Comment by Carrotzpc** [comment]
已使用新封装的组件实现：
https://yuntijs.github.io/yunti-ui/components/slider-input/
