### ISSUE TITLE
[Request] 知识库支持配置ChunkSize和ChunkOverlap。 默认为 1024， 100

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/ops-console#251]
### 🥰 需求描述 | Feature Description

知识库支持配置ChunkSize和ChunkOverlap。 默认为 1024， 100

### 🧐 解决方案 | Proposed Solution

知识库支持配置ChunkSize和ChunkOverlap。 默认为 1024， 100

**Comment by liutianyi0801** [comment]
1、该配置是针对文件，还是针对一个知识库？如：创建知识库时，配置的是：1024/100，第一次上传了 10 个文件，均按 1024/100 进行分段；第二次上传新的知识文件时，还是按 1024/100 分段，还是支持重新配置分段？（如果要加，是否针对文件进行分段合理一些？）
2、该配置是否仅对文本类型的文件生效？如：pdf、doc、md 等，对 csv 等其他文件应该不生效？

**Comment by bjwswang** [comment]
对知识库生效，还不支持细粒度的配置。

目前只支持 pdf，md
