### ISSUE TITLE
对话框上传大文件

### ISSUE THREAD

**Issue by liutianyi0801** [kubeagi/ops-console#252]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

测试大文件摘要时，上传文件失败。
![image](https://github.com/kubeagi/ops-console/assets/76506250/e218c71a-15d7-4a3e-ac89-ef0ca12ce51e)
这个文件约 20M（约 300 页 PDF），我们现在上传文件最大限制是多大呀？

**Comment by liutianyi0801** [comment]
@bjwswang

**Comment by bjwswang** [comment]
finished by increasing proxy-body-size
