### ISSUE TITLE
知识库支持删除文件

### ISSUE THREAD

**Issue by liutianyi0801** [kubeagi/ops-console#255]
### 🥰 需求描述 | Feature Description

现知识库不支持删除文件，需要支持文件的删除
![image](https://github.com/kubeagi/ops-console/assets/76506250/ba6a2776-f8ca-4fea-b2ad-f71191215246)

优先级：P0

### 🧐 解决方案 | Proposed Solution

略

**Comment by liutianyi0801** [comment]
@bjwswang

**Comment by Carrotzpc** [comment]
resolved in 11ffd9a63fffcb88d221bd0c9deaca04ffea4667
