### ISSUE TITLE
知识库新增的文件没有出现在列表中

### ISSUE THREAD

**Issue by liutianyi0801** [kubeagi/ops-console#257]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

1、新增知识库时，文件列表没有文件数据
2、知识库新增的文件没有出现在列表中

可能原因：貌似仅展示了处理后的文件，如：成功、失败，处理中的没有出现在列表中
![image](https://github.com/kubeagi/ops-console/assets/76506250/720b4afb-ab7c-452b-aef0-e66bf1c8fa84)

### 🚦 期望结果 | Expected Behavior

期望能够展示所有关联的文件

**Comment by liutianyi0801** [comment]
@bjwswang 分配一下任务吧~

**Comment by bjwswang** [comment]
finished by @0xff-dev
