### ISSUE TITLE
新增知识库时，确认后文件预览状态不对

### ISSUE THREAD

**Issue by liutianyi0801** [kubeagi/ops-console#258]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

新增知识库时，确认后文件预览状态直接变成绿色（这是成功的颜色），但是返回列表后，文件正在处理中/处理失败，所以这个状态是对不上的

![image](https://github.com/kubeagi/ops-console/assets/76506250/2f1dafb1-ed3f-4ee5-89bd-1e884e85cde9)

![image](https://github.com/kubeagi/ops-console/assets/76506250/155d0250-d092-4d56-9ba5-d9a4a31fef36)

![image](https://github.com/kubeagi/ops-console/assets/76506250/7ef998a8-ec7d-4a85-8b89-6464be9d555b)

![image](https://github.com/kubeagi/ops-console/assets/76506250/624ed362-be23-47e6-9b45-3285303d8334)

**Comment by liutianyi0801** [comment]
@bjwswang

**Comment by Carrotzpc** [comment]
建议知识库创建完成后直接进入知识库详情页，目前停留在创建的预览页面意义不大@liutianyi0801

**Comment by liutianyi0801** [comment]
可以直接进入知识库详情页面，不过从详情页返回时，需要返回到列表页面，而不是新建页面
@Carrotzpc

**Comment by bjwswang** [comment]
已完成
