### ISSUE TITLE
知识库详情无法新增文件

### ISSUE THREAD

**Issue by liutianyi0801** [kubeagi/ops-console#259]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

知识库详情无法新增文件
![image](https://github.com/kubeagi/ops-console/assets/76506250/20da7f3b-1a25-4785-b108-02b00b31c181)

**Comment by liutianyi0801** [comment]
@bjwswang

**Comment by Carrotzpc** [comment]
我试了下是可以的，是不是数据集有问题？

**Comment by Carrotzpc** [comment]
我这边也复现了，原因是处理中的这种知识库，没有返回 `fileGroupDetails`，获取不到数据集的名称，所以请求不到数据集里的内容@bjwswang
![image](https://github.com/kubeagi/ops-console/assets/10265417/994c2583-b494-44d0-9fd5-a37415aa13a7)

**Comment by bjwswang** [comment]
已完成
