### ISSUE TITLE
GPTs 平台对话记录需要支持展示智能体

### ISSUE THREAD

**Issue by liutianyi0801** [kubeagi/ops-console#282]
### 🥰 需求描述 | Feature Description

现在对话展示的头像还是默认头像，需要展示对应的智能体头像
![image](https://github.com/kubeagi/ops-console/assets/76506250/3eb34c8d-d1d0-4103-a8fb-69d31b93d516)

### 🧐 解决方案 | Proposed Solution

略

### 📝 补充信息 | Additional Information

优先级 P0

**Comment by liutianyi0801** [comment]
@Abirdcfly

**Comment by Carrotzpc** [comment]
目前 api 应该没有返回头像信息，需要先返回下，目前头像好像是 base64 的方式返回的，性能会比较差，后续可以考虑优化下

**Comment by Carrotzpc** [comment]
@Vision 处理下这个 jira
